### ISSUE TITLE
Porting to 64-bit

### ISSUE THREAD

**Issue by Mic92** [yalue/elf32_string_replace#3]
Are you aware of any roadblocks except the obviously different elf headers that could come up when porting it to 64 bit?

**Comment by yalue** [comment]
I am not aware of any such roadblocks, and I'd expect the high-level procedure to be identical for both types of files.  I've even updated the `github.com/yalue/elf_reader` package to support 64-bit ELF files, so perhaps porting this to 64-bit would be as "simple" as changing the offsets and addresses from `uint32`s to `uint64`s, and changing the `elf_reader.ELF32...` portions to `elf_reader.ELF64...`.  No guarantees, of course!  I haven't looked at this code in a long time.
